version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: myid/gianyar_app
    container_name: app
    links:
      - db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - 8081:80
